### PR TITLE
Fix comment typos/text, refactor if-else chains to switch statements, optimize return statements, and invert conditional logic

### PR DESCRIPTION
**Pull request by wilari932**
This pull request focuses solely on minor yet effective tweaks aimed at bolstering the readability.
Key Updates:

Corrected typos within code comments.
Transitioned from some if-else to switch statements.
Refined return statements for straightforward execution paths.
Streamlined conditional logic by inverting some if statements.

### CODE REVIEW

**Comment by wilari932** [comment]
@microsoft-github-policy-service agree

**Comment by wilari932** [comment]
@microsoft-github-policy-service agree

**Comment by wilari932** [comment]
> @wilari932 please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @dotnet-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @dotnet-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @dotnet-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

**Comment by wilari932** [comment]
@dotnet-policy-service agree

**Comment by chkr1011** [comment]
@wilari932 Usually I do not accept such PR because changing the code style has often no benefit and depends only on personal preferences. But since it also contains type fixes, I will still accept it.

But I made some small adjustments. If you agree I will merge the PR.

**Pull request merged**
