### PR TITLE
UseDefaultCredentials options for WebSockets proxy configuration.

### PR DESCRIPTION
**Pull request by impworks**
This PR adds an option to pass `UseDefaultCredentials` option to the `WebProxy` used by WebSockets implementation.

### CODE REVIEW

**Comment by impworks** [comment]
@dotnet-policy-service agree

**Comment by chkr1011** [comment]
I exposed a few more options. Please let me know what you think and if it works?

**Comment by impworks** [comment]
@chkr1011 LGTM

**Comment by impworks** [comment]
@chkr1011 could you please tell me when this change will be included in the next NuGet package version?

**Comment by chkr1011** [comment]
The new version will be released within the next days. Probably next weekend.

**Pull request merged**
