### PR TITLE
Notify what subscription topics failed as part of the SynchronizingSu…

### PR DESCRIPTION
**Pull request by scottbrogden-iheartmedia**
We needed a way to retry adding subscriptions to aws, we have ran into rate limits in aws that we are trying to work around.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/MQTTnet?pullRequest=1678) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/MQTTnet?pullRequest=1678) before we can accept your contribution.<br/><br/>:x: scottbrogden-iheartmedia [sign now](https://cla.dotnetfoundation.org/dotnet/MQTTnet?pullRequest=1678)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/MQTTnet?pullRequest=1678) it.</sub>

**Comment by chkr1011** [comment]
@scottbrogden-iheartmedia Please agree to the license agreement. Then we can merge the PR.

**Comment by scottbrogden-iheartmedia** [comment]
@dotnet-policy-service agree [company="iheartmedia"]

**Comment by scottbrogden-iheartmedia** [comment]
@dotnet-policy-service agree company="IHeartMedia"

**Pull request merged**
